-- 2026-05-19: Add-ons migrated to MCP servers, per Sophie's UX brief.
-- Notion / Obsidian / Web Search are now installed via Settings →
-- MCP servers (Quick-add catalog). Drop their addon rows so the
-- Add-ons page doesn't shadow the MCP entries.
--
-- Kept:
--   - Voice Mode             (refactor pending)
--   - Hermes Agent           (UI label: "Cluster Operations")
--   - Voice (Gemini Live)    (refactor pending)
-- Plus the LiteLLM card which is backed by users.litellm{Url,…} and
-- has no addons-row counterpart.
DELETE FROM addons WHERE name IN ('Notion', 'Obsidian', 'Web Search');
